spring:
  application:
    name: hospital

  jpa:
    hibernate:
      ddl-auto: update
      #      ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          #format_sql: true

  datasource:

    #    Main
    #    url: jdbc:mysql://hometract-maindb.czqskiy84lhw.ap-northeast-2.rds.amazonaws.com:3306/hometract
    #    username: admin
    #    password: hBSAPA0Q20Gj0UzCPfQF

    #    kdy
    url: jdbc:mysql://localhost:3306/Hospital
    username: root
    password: ehd5765613

    #    JHL
    #    url: jdbc:mysql://localhost:3306/hometract
    #    username: root
    #    password: asd990810

    driver-class-name: com.mysql.cj.jdbc.Driver