spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:

    url: jdbc:mysql://3.34.15.114:3306/hospital
    username: root
    password: asd990810
#    url: jdbc:mysql://localhost:3306/hospital
#    username: root
#    password: asd990810

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          jdbc:
            time-zone: Asia/Seoul

  sql:
    init:
      mode: always