apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app-green
  labels:
    app: hospital-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-app
      version: green
  template:
    metadata:
      labels:
        app: hospital-app
        version: green
    spec:
      containers:
        - name: hospital-app
          image: jonghyunleee/stmary:green
          ports:
            - containerPort: 8080