apiVersion: v1
kind: Service
metadata:
  name: hospital-app-service
spec:
  selector:
    app: hospital-app
    version: blue  # 초기에는 블루로 트래픽 설정
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer