export const ITEMS_NAME_MAP: { [key: string]: string } = {
    explainBeforeOperation: 'EAS 수술전 설명',
    takingONSBeforeOperationTwo_Hours: '수술 2시간 전 ONS 복용여부',
    takingAfterBowelPreparation: 'Bowel preparation 후 ONS 경장영양액 복용여부',
    preventionDVT: 'DVT 예방',
    takingLaxatives: 'Laxatives 복용',
    chewingGum: 'Chewing gum',
    dayOfRemoveJP_Drain: 'JP Drain 제거일',
    reasonByRemoveJP_DrainDelay: 'JP Drain 제거 지연 사유',
    dayOfRemoveUrinary_Catheter: 'Urinary catheter 제거일',
    reasonByRemoveUrinary_CatheterDelay: 'Urinary catheter 제거 지연 사유',
    afterOperationLimitIV_Fluid: '수술 후 IV fluid 제한',
    dayOfRemoveIV_Fluid: 'IV fluid 제거일',
    reasonByRemoveIV_FluidDelay: 'IV fluid 제거 지연 이유',
    post_Nausea_Vomiting: 'Post OP Nausea & Vomiting prophylaxis',
    postOpDayExercise: 'Post OP day 운동',
    pod_Exercise: 'POD# 운동',
    postOpDayMeal: 'Post OP day 식사',
    pod_Meal: 'POD# 식사',
    beforeOperationMedicine: '수술 전 통증 조절약',
    silt_Itm: '수술중 SILT or ITM',
    postOpEffectivePainControl: 'Post op Effective pain control',
    pod_PainScore: 'POD# pain scroe',
    beforeSixtyMinute: '피부 절개 60분 전 예방적 항생제 투여',
    maintainTemperature: '수술 중 환자 체온 유지',
    volumeOfIntraoperativeInfusion: 'Volume of intraoperative infusion (ml)',
    bloodLoss: 'Blood loss (cc)',
    urineOutput: 'Urine output (cc)',
    operationTime: 'Operation time (min)',
    hasPost_Nausea_Vomiting: 'Post OP Nausea & Vomiting prophylaxis 여부',
    locate: '입원병동',
};
